### ISSUE TITLE
Rename repository name

### ISSUE THREAD

**Issue by filhocf** [dapphp/Roundcube-Plugin-attachment_position#2]
Hi @dapphp 

I saw some roundcube plugin developers align your plugin project names to "roundcube-<name>".

So, I suggest to you rename this project to "roundcube-attachment_position".

And thanks by your work.

**Comment by dapphp** [comment]
Hi,

Thanks for adding the translation.  I agree the roundcube-plugin-name convention seems to be more widely adopted with current plugins.

I have renamed the repo.

Thanks!

**Comment by wesch3al** [comment]
I was wondering if there is a way to allow your plugin to work on "inbox" attachments? I would like to move the attachments on the right side to the left above the message content running in a row instead of a column? Or is there an easier way with modifing the php file or using css? Actually, what I want to do is move the attachment to the bottom of the message header like the Attachment_Position plugin does when you compose an email.
